Select SNAME.SKDNAME as 'Schedule Name', JMASTER_AUX.JOBNAME, JMASTER_AUX.JAVALUE AS 'Command Line' , convert(datetime,HISTORY.SKDDATE + -2) AS 'Last Run On', HISTORY.JRUN AS 'RunTime'
from JMASTER_AUX 
INNER JOIN SNAME on JMASTER_AUX.SKDID = SNAME.SKDID 
INNER JOIN HISTORY ON JMASTER_AUX.JOBNAME = HISTORY.JOBNAME
WHERE JMASTER_AUX.JAFC = 3003 and JMASTER_AUX.JAVALUE LIKE '%dtsrun%' and SNAME.SKDID <> 138
	OR JMASTER_AUX.JAFC = 3003 and JMASTER_AUX.JAVALUE LIKE '%dtexec%' and SNAME.SKDID <> 138
ORDER BY SKDNAME,JOBNAME
