select JOBNAME,PRIMMACHID, (DATEDIFF(mi,STARTSTAMP,LASTUPDATE)) AS "TIMERUNNING",TERMDESC, SKDDATE,STARTSTAMP,LASTUPDATE FROM SMASTER
WHERE DAY(CURRENT_TIMESTAMP) + 2 = DAY(SKDDATE) and JOBSTATUS = 500 AND SKDID <> 11 
-----
select SMASTER.JOBNAME,
MACHS.MACHNAME,
(DATEDIFF(mi,SMASTER.STARTSTAMP,SMASTER.LASTUPDATE))
AS "TIMERUNNING",SMASTER.TERMDESC, SMASTER.SKDDATE,SMASTER.STARTSTAMP,SMASTER.LASTUPDATE
FROM [OPCONXPS].[dbo].[SMASTER] JOIN [OPCONXPS].[dbo].[MACHS]
ON (SMASTER.PRIMMACHID = MACHS.MACHID)
WHERE DAY(CURRENT_TIMESTAMP) + 2 = DAY(SKDDATE) and SMASTER.JOBSTATUS = 500 AND SMASTER.SKDID <> 11
---

select SMASTER.JOBNAME,
SMASTER.JOBSTATUS,
MACHS.MACHNAME,
DATEDIFF(mi,SMASTER.STARTSTAMP,SMASTER.LASTUPDATE) AS "TIMERUNNING",
SMASTER.TERMDESC,
CASE DAY(SMASTER.SKDDATE) 
-- DAY(SMASTER.SKDDATE) - 2 AS 'Date', 
    WHEN DAY(CURRENT_TIMESTAMP) + 2 THEN  'Today' 
    ELSE CAST(SMASTER.SKDDATE AS datetime)    
    END as 'Date', 
SMASTER.STARTSTAMP ,
SMASTER.LASTUPDATE
FROM [OPCONXPS].[dbo].[SMASTER] JOIN [OPCONXPS].[dbo].[MACHS]
ON (SMASTER.PRIMMACHID = MACHS.MACHID)
WHERE SMASTER.SKDID <> 11 
AND SMASTER.JOBSTATUS = 900
--AND DAY(SMASTER.SKDDATE) = DAY(CURRENT_TIMESTAMP) + 2  
ORDER BY SMASTER.SKDDATE
---
select SMASTER.JOBNAME,
SMASTER.JOBSTATUS,
MACHS.MACHNAME,
DATEDIFF(mi,SMASTER.STARTSTAMP,SMASTER.LASTUPDATE) AS "TIMERUNNING",
SMASTER.TERMDESC,
CASE DAY(SMASTER.SKDDATE)  
    WHEN DAY(CURRENT_TIMESTAMP) + 2 THEN  'Today'  -- should probably remove this block to keep the date column sane 
    ELSE CAST(SMASTER.SKDDATE AS datetime)    
   END as 'Date', 
CAST(SMASTER.STARTSTAMP - 2 AS datetime) AS "Start time",
CAST(SMASTER.LASTUPDATE - 2 AS datetime) AS "end_time"
FROM [OPCONXPS].[dbo].[SMASTER] JOIN [OPCONXPS].[dbo].[MACHS]
ON (SMASTER.PRIMMACHID = MACHS.MACHID)
WHERE SMASTER.SKDID <> 11  -- 11 is the SMAUtility schedule
AND SMASTER.JOBSTATUS = 900   -- 900 completed successfully, 500 still running
--AND DAY(SMASTER.SKDDATE) = DAY(CURRENT_TIMESTAMP + 2) -- +2 = today, +1 = yesterday.. etc 
--AND MACHNAME = 'MIMRXDEV'
--ORDER BY SMASTER.SKDDATE
ORDER BY SMASTER.STARTSTAMP
----------------------
--finding job
select 
         JOBNAME,
         CAST(SKDDATE - DAY(1) AS DATETIME) AS "Date",
         --JTERM, 
         JRUN AS "Run Time", 
         JMACH AS "Machine",
         JDESC AS "Termination Code" 
  from 
         history 
  where 
         JOBNAME like 'Ter%' AND 
         JMACH = 'RCW2SCHMDSQL'           
  ORDER BY  
         Date DESC